### ISSUE TITLE
Notificar Resultados por SMS/WhatsUP

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#104]
Se usuário autenticado for Gestor
    1) Abrir lista de Histórico de Exames aparecendo um checkbox em cada coluna da tabela e outro campo mostrando se já foi enviada notificação daquele exame (noco campo booleano na tabela exame).
    2) Surgirá também um novo botão "Notificar" na parte superior da tela
    3) Gestor Seleciona os resultados de exames que ele deseja notificar
    4 Pressiona o botão Notificar
    5) Aparece popup de confirmação: 
           Deseja Notificar Resultados de Exames? Botões SMS, WhatsUP e Cancelar.
    6) Se pressionar SMS ou WhatsUP
          6.1) Verifica na Tabela Notificar se a Empresa/Estado/Municipio possui um chave valida
                  Caso possua, envia.
                  Caso não possua, envia mensagem:
                     "Você não possui créditos suficientes no Twilio para realizar as notificações. Por favor entre em contato com a Fábrica de Software através do email fabricadesoftware@ufs.br para orientarmos no cadastro.  "
       7) Atualiza campo de notificação = true
 
Mensagem Resultado Positivo: Olá, aqui é o grupo da pesquisa da UFS, onde você fez o exame de COVID-19, seu resultado foi POSITIVO "REAGENTE PARA ESTE TESTE". Mantenha as orientações do Ministério da Saúde! Obrigado pela sua participação. Entraremos em contato ainda hoje! Mantenha o isolamento social.
Mensagem Resultado Negativo: Olá, aqui é o grupo da pesquisa da UFS, onde você fez o exame de COVID-19, seu resultado foi NEGATIVO "NÃO REAGENTE NESTE TESTE". Mantenha as orientações do Ministério da Saúde! Obrigado pela sua participação

**Comment by gabriel-sisjr** [comment]
PR #128
