### ISSUE TITLE
Implementar Menu Principal da Aplicação por Perfil

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#14]
Opções do Perfil Secretário de Saúde:
Notificar Resultado Exame
Listar Resultados Exame 
Monitorar Pacientes
Gerenciar Coordenadores
Gerenciar Agentes de Saúde
Gerenciar Agentes em Laboratórios
Manter Laboratórios

Opções do Perfil Coordenador:
Notificar Resultado Exame
Listar Resultados Exame
Monitorar Pacientes
Gerenciar Agentes de Saúde
Gerenciar Agentes em Laboratórios
Manter Laboratórios

Opções do Perfil Agente:
Notificar Resultado Exame
Listar Resultados Exame

**Comment by gabriel-sisjr** [comment]
Fixed in PR #20
