### ISSUE TITLE
Ocultar Campos Quando não necessários no Exame (Inserir e Editar)

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#145]
Ocultar os combobox de sintomas quando no registro de exame o campo "relatou sintomas" = false

Na seção Resultados
Quando selecionar Método Fluorescencia -> Habilitar IgG e IgM e Ocultar os demais
Quando selecionar Método I.Cromatografia -> Habilitar IgG, IgM, e IgGIgM e ocultar PCR
Quando selecionar Método RT-PCR -> Habilitar apenas o PCR e ocultar os demais

**Comment by igorb22** [comment]
Fix #145
