### ISSUE TITLE
Adicionar Internações do Paciente no Monitoramento

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#146]
Deve ser possível inserir, editar e excluir uma internação
Deve-se selecionar o hospital, a data de inicio, o tipo de ventilação utilizada e opcionalmente a data de fim do internamento.
A grid com a lista de internações do paciente deve ser exibida na seção "Saúde do Paciente"

**Comment by igorb22** [comment]
Fix #146
