### ISSUE TITLE
Correção na busca da Latitude e Longitude de alguns endereços

### ISSUE THREAD

**Issue by marcosdosea** [fabricadesoftwareufs/MonitoraSUS#150]
Quando endereço for retornado pelo cep, fazer a busca na classe Service da seguinte forma:
1. Buscar na api do maps a latitude e longitude usando os dados país+estado+cidade+bairro+rua+numero.
2. Buscar latitudePadrao e longitudePadrao na tabela municipiogeo do município selecionado
3. Se (Math.Abs(latitude - latitudePadrao) > 10 || Math.Abs(longitude - longitudePadrao) > 10 || latitude = 0 || longitude = 0)
    latitude = latitudePadrao
    longitude = longitudePadrao

**Comment by fabricadesoftwareufs** [comment]
Isso ainda precisa ser implementado. Esse método deve ser adicionado em exameService. E chamado dos métodos insert, update e import.
