### ISSUE TITLE
Importar Planilha GAL

### ISSUE THREAD

**Issue by marcosdosea** [fabricadesoftwareufs/MonitoraSUS#151]
1) Criar para os gestores a opção no menu Importar Planilha GAL
2) Criar nova tela com a seguinte mensagem...
Gere a planilha do GAL selecionando todos os campos disponíveis e faça o upload do arquivo .csv gerado. Caso um exame já tenha sido importado para base de dados do MonitoraSUS, os dados serão apenas atualizados.
Selecione Planilha do GAL: ____________  | Upload |
3) Regras para importação da planilha
a) Criar sempre um temporário para o cpf do paciente
b) Criar um novo campo CNS - Carteira Nacional SUS. Esse campo é opcional mas pode ser usado como identificador do paciente. Na busca por um paciente deve-se olhar o cpf/identidade e caso sejam temporário, deve-se verificar a existência do CNS do paciente.
c) Endereço, quando preenchido, deve-se tentar buscar a latitude e longitude na classe service. Caso não seja preenchido ou encontrado, deve usar a latitude e longitude padrão da tabela municipioGEO
d) Se bairro não preenchido, deve-se usar o bairro "NÃO INFORMADO"
e) O número do campo requisição deve ser colocado no campo idcoleta no formato GAL<Requisicao> 
f) O número idcoleta deve ser consultado sempre antes de criar um novo exame na tabela. Caso o exame já exista, ele deve ser atualizado.
g) Deve-se vincular o exame a idEmpresa na tabela exame. Caso a empresa não cadastrada, deve-se cadastrar automático na importação, mesmo com os dados incompletos. Adicionar o campo CNES a empresa. Ele deve ser usado para busca da empresa caso a empresa não possua cnpj informado. É possível ter várias empresas com CNPJ "Não Informado".

**Comment by fabricadesoftwareufs** [comment]
Fazer novos testes depois das alterações que foram realizadas na arquitetura do sistema.

**Comment by igorb22** [comment]
Fiz um novo PR, dê uma olhada. Se atente aos comentários que fiz sobre a importação.

**Comment by marcosdosea** [comment]
PR adicionada ao master.
