### ISSUE TITLE
Adicionar Data Anottations nos Models para Validar campos nos Formulários

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#153]
Remover validações com código javascript
Adicionar anotações nos ViewModel 
  - Required: em todos os campos obrigatórios
  - StringLength - em todos os campos String
  - Criar validações específicas para CNPJ e outros campos necessários. Usar como exemplo a validação do CPF
Adicionar tag de validação nos Formulários

**Comment by marcosdosea** [comment]
Feito!
