### ISSUE TITLE
Atualizar Tela de Confirmação de Notificação

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#157]
Na inserção e edição de exames a confirmação de notificação exibe resultado do exame baseado em javascript. Código duplicado e sujeito a falta de sincronização. Dessa forma:
1) Remover javascript que define o resultado do exame
2) Exibir resultado baseado no calculado na classe ExameModel

**Comment by marcosdosea** [comment]
evoluiu isso @igorb22
