### ISSUE TITLE
Implementar Comunicação pelo WhatsApp e SMS

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#25]
- Notificar Resultados de Exames
- Envio de senhas 
- Renovação de senhas

**Comment by gabriel-sisjr** [comment]
@fabricadesoftwareufs alguma lib em mente?!

**Comment by fabricadesoftwareufs** [comment]
Essa função será usada por enquanto apenas para reenvio de senha e resultados de exames solicitados pela tela de login. Não será mais usada para enviar resultados de todos os exames notificados.

**Comment by abralvs** [comment]
fechada até ser pertinente

**Comment by gabriel-sisjr** [comment]
Closed in PR #128
