### ISSUE TITLE
Correções Busca Endereço pelo CEP

### ISSUE THREAD

**Issue by fabricadesoftwareufs** [fabricadesoftwareufs/MonitoraSUS#40]
- Deve usar o via CEP também quando digitar o padrão 99999-999
- Ao digitar o cep 49050485 ele preenche o campo complemento e não deixa alterar. O Campo complemento não deve ser de autopreenchido. Deve ser sempre de livre digitação.
- Mesmo digitando números no campo de pesquisa ele continua chamado o autocomplete do google. Teria como desabilitar? O autocomplete só deveria ser chamado se digitar um número diferente do padrão 99999-999 ou 99999999.
- Se selecionar um endereço do autocomplete do google é possível usar o viacep para buscar e fazer o autopreenchimento do bairro?
- Se selecionar um endereço do autocomplete do google e coloca o número da residência é possível atualizar o cep? E em seguida atualizar o bairro? Tem ruas com vários ceps e em bairro distintos.

**Comment by gabriel-sisjr** [comment]
Reabrindo para término da ISSSUE.

**Comment by gabriel-sisjr** [comment]
Fechando Issue de acordo com as anotações no PR #53
